### PR TITLE
[fixes #427] - NIOLockProvider will not retry when failing to create output stream

### LINKED ISSUE #427: NIOLockProvider will not retry when failing to create output stream
If NIOLockProvider fails to create output stream client gets empty tiles:

HTTP error code 400: "Failure while trying to get lock for key meta_{tile}.png"

GeoWebCache v1.9.1

```
currFos = new FileOutputStream(file);

try {
  currLock = currFos.getChannel().lock();
 } catch (OverlappingFileLockException e) {
    IOUtils.closeQuietly(currFos);
...
```

Moving `currFos = new FileOutputStream(file);` into the try would solve the issue.

### PR DESCRIPTION
**Pull request by emilzse**
* Moved initialization of FileOutputStream into try to retry on exceptions
* Added possibility to configure waitBeforeRetry and maxLockAttempts as constructor args
* Will use waitBeforeRetry in thread sleep

### CODE REVIEW

File: geowebcache/core/src/main/java/org/geowebcache/locks/NIOLockProvider.java [hunk 1]
```diff
@@ -73,21 +84,22 @@ public NIOLockProvider(String root) throws ConfigurationException {
                 while(currLock == null && count < maxLockAttempts) {
                     // the file output stream can also fail to be acquired due to the
                     // other nodes deleting the file
-                    currFos = new FileOutputStream(file);
                     try {
+                        currFos = new FileOutputStream(file);
+
                         currLock = currFos.getChannel().lock();
                     } catch(OverlappingFileLockException e) {
                         IOUtils.closeQuietly(currFos);
```
Comment (smithkm) [inline geowebcache/core/src/main/java/org/geowebcache/locks/NIOLockProvider.java]: This shouldn't be needed now that try-with-resources is being used.

File: geowebcache/core/src/main/java/org/geowebcache/locks/NIOLockProvider.java [hunk 2]
```diff
@@ -73,21 +84,22 @@ public NIOLockProvider(String root) throws ConfigurationException {
...
                         try {
-                            Thread.sleep(20);
+                            Thread.sleep(waitBeforeRetry);
                         } catch (InterruptedException ie) {
                             // ok, moving on
                         }
                     } catch(IOException e) {
                         // this one is also thrown with a message "avoided fs deadlock"
                         IOUtils.closeQuietly(currFos);
```
Comment (smithkm) [inline geowebcache/core/src/main/java/org/geowebcache/locks/NIOLockProvider.java]: Likewise shouldn't be needed now

File: geowebcache/core/src/main/java/org/geowebcache/locks/NIOLockProvider.java (hunk 1 above)
Comment (emilzse) [inline geowebcache/core/src/main/java/org/geowebcache/locks/NIOLockProvider.java]: try-with-resource is not suitable solution here since the stream should not be closed if successfully created inside the try

Comment (smithkm) [inline geowebcache/core/src/main/java/org/geowebcache/locks/NIOLockProvider.java]: OK.  Only criticism remaining then is the need for a unit test.

**Comment by smithkm** [comment]
Since this is a bug fix, not a feature, it is not affected by the feature freeze.  Getting it in before the freeze would still be nice, but it can be merged after.

**Comment by smithkm** [comment]
OK looked at making a unit test and it's probably not worth the trouble for this fix.
